packages:
  - apps/*
  - packages/*

allowBuilds:
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@prisma/client'
  - argon2
  - '@prisma/engines'
  - esbuild
  - prisma
  - unrs-resolver
