module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testEnvironment: 'node',
  testMatch: ['<rootDir>/test/**/*.spec.ts'],
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.json' }],
  },
  moduleNameMapper: {
    '^@solis/admin-contracts$': '<rootDir>/../../packages/admin-contracts/src/index.ts',
    '^@solis/database$': '<rootDir>/../../packages/database/src/index.ts',
  },
  collectCoverageFrom: [
    'src/charging/domain/*.ts',
    'src/charging/charging-realtime.gateway.ts',
    'src/auth/jwt-auth.guard.ts',
    'src/admin/access/admin-auth.service.ts',
    'src/admin/access/admin-permission.guard.ts',
    'src/admin/audit/admin-audit.service.ts',
    'src/common/correlation-id.middleware.ts',
    'src/charging/gateway/charger-event-relay.ts',
    'src/charging/gateway/ocpp16-charger.gateway.ts',
    'src/charging/gateway/routing-charger.gateway.ts',
    'src/ocpp/*.ts',
    'src/payments/**/*.ts',
    '!src/payments/**/*.controller.ts',
    '!src/payments/**/*.module.ts',
    '!src/payments/**/dto/*.ts',
  ],
  coverageDirectory: 'coverage',
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 70,
      functions: 75,
      lines: 80,
    },
    './src/payments/money/**/*.ts': {
      statements: 95,
      branches: 90,
      functions: 95,
      lines: 95,
    },
  },
};
