module.exports = {
  preset: 'jest-expo',
  clearMocks: true,
  collectCoverageFrom: [
    'src/utils/qr-parser.ts',
    'src/config/runtime.ts',
    'src/auth/token-storage.ts',
    'src/logging/AppLogger.ts',
    'src/config/maps.ts',
    'src/location/LocationService.ts',
    'src/location/useUserLocation.ts',
    'src/stations/discovery.ts',
    'src/garage/vehicle-catalog.ts',
    'src/stations/clustering.ts',
    'src/navigation/external-maps.ts',
    'src/hooks/useDebouncedValue.ts',
    'src/stores/map-store.ts',
    'src/components/StationMapMarker.tsx',
    'src/components/StationPreviewCard.tsx',
    'src/dashboard/periods.ts',
    'src/history/query-keys.ts',
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 70,
      functions: 75,
      lines: 80,
    },
  },
  setupFiles: ['<rootDir>/jest.setup.js'],
  testMatch: ['**/__tests__/**/*.spec.ts', '**/__tests__/**/*.spec.tsx'],
  moduleNameMapper: {
    '^@solis/design-tokens$': '<rootDir>/../../packages/design-tokens/src/index.ts',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
};
